package cn.yurin.mcl.core

fun buildGameProcess(
	java: String,
	launcherBrand: String?,
	launcherVersion: String?,
	classpath: List<String>,
	minecraftJar: String,
	mainClass: String,
	gameDir: String,
	assetDir: String,
	assetIndex: String,
	username: String?,
	uuid: String,
	accessToken: String,
	version: String,
): ProcessBuilder {
	return ProcessBuilder(
		java,
		"-Dminecraft.launcher.brand=$launcherBrand",
		"-Dminecraft.launcher.version=$launcherVersion",
		"-cp",
		listOf(*classpath.toTypedArray(), minecraftJar).joinToString(";"),
		mainClass,
		"--gameDir",
		gameDir,
		"--assetsDir",
		assetDir,
		"--assetIndex",
		assetIndex,
		"--username",
		username,
		"--uuid",
		uuid,
		"--accessToken",
		accessToken,
		"--version",
		version,
		"--versionType",
		"MCL",
	)
}